# Generated by Django 5.2.15 on 2026-06-22 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('product_view', 'Product view'), ('add_to_cart', 'Add to cart'), ('remove_from_cart', 'Remove from cart'), ('begin_checkout', 'Begin checkout'), ('purchase', 'Purchase'), ('account_created', 'Account created'), ('login', 'Login'), ('b2b_stock_viewed', 'B2B stock viewed'), ('reorder_clicked', 'Reorder clicked'), ('customization_started', 'Customization started'), ('quote_simulated', 'Quote simulated'), ('quote_requested', 'Quote requested'), ('b2b_request_submitted', 'B2B request submitted')], max_length=40)),
                ('channel', models.CharField(blank=True, choices=[('b2c', 'B2C'), ('b2b', 'B2B')], default='', max_length=3)),
                ('canton', models.CharField(blank=True, default='', max_length=2)),
                ('campaign_period', models.CharField(blank=True, default='', max_length=50)),
                ('value_chf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_c3dcde_idx'), models.Index(fields=['channel', 'created_at'], name='analytics_e_channel_91a4a7_idx'), models.Index(fields=['canton'], name='analytics_e_canton_0b8340_idx')],
            },
        ),
    ]
