# Generated by Django 5.2.15 on 2026-06-11 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom de la catégorie (ex: Chocolats noirs)', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly version du nom (auto-generated)', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom du produit', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly version du nom', unique=True)),
                ('short_description', models.TextField(help_text='Description courte (pour listing produits)')),
                ('description', models.TextField(help_text='Description longue (pour détail produit)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix en CHF (ex: 12.50)', max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, default=100, help_text='Poids en grammes (ex: 100)', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Publié sur le site ? (False = caché)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Catégorie du produit', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Fichier image (JPEG, PNG)', upload_to='products/')),
                ('alt_text', models.CharField(help_text="Description de l'image (pour SEO et accessibilité)", max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Cette image est-elle la principale ?')),
                ('product', models.ForeignKey(help_text='Produit auquel appartient cette image', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, help_text="Nombre d'unités disponibles")),
                ('minimum_threshold', models.PositiveIntegerField(default=10, help_text='Alerte si quantité < ce nombre')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Dernière modification du stock')),
                ('product', models.OneToOneField(help_text='Produit', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='shop.product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
