# Generated by Django 5.2.15 on 2026-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='cost_chf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Production cost in CHF (for margin KPI)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='flavor',
            field=models.CharField(blank=True, default='', help_text='Flavor variant (e.g. pistache, coffee, caramel)', max_length=100),
        ),
    ]
