# Generated by Django 5.2.15 on 2026-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sku_cost_chf_sku_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
