# Generated by Django 5.2 on 2026-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_stock_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sku",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("CHF", "Franc suisse")],
                default="CHF",
                max_length=3,
            ),
        ),
    ]
