# Generated by Django 5.2.15 on 2026-06-14 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique du client (UUID)', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email unique du client', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Prénom du client', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='Nom de famille du client', max_length=150)),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone (format: +41 XX XXX XX XX)', max_length=20)),
                ('company_name', models.CharField(blank=True, help_text="Nom de l'entreprise (si client B2B)", max_length=255)),
                ('is_b2b', models.BooleanField(default=False, help_text="Vrai si c'est un client B2B (professionnel)")),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('de-ch', 'Deutsch (Schweiz)'), ('it-ch', 'Italiano (Svizzera)')], default='fr', help_text='Langue préférée du client', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Le compte est-il actif ? (False = compte suspendu)')),
                ('is_staff', models.BooleanField(default=False, help_text="Accès à l'interface admin (/admin/)")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du compte')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Token aléatoire envoyé par email', max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Date d.expiration du token (1h)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du token')),
                ('is_used', models.BooleanField(default=False, help_text='True si le token a déjà été utilisé')),
                ('customer', models.ForeignKey(help_text='Client qui demande la réinitialisation', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
