# Generated by Django 5.2.15 on 2026-06-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={},
        ),
        migrations.AddField(
            model_name='customer',
            name='canton',
            field=models.CharField(blank=True, choices=[('VD', 'Vaud'), ('GE', 'Genève'), ('ZH', 'Zürich'), ('BE', 'Bern'), ('VS', 'Valais'), ('FR', 'Fribourg'), ('NE', 'Neuchâtel'), ('JU', 'Jura'), ('TI', 'Ticino'), ('XX', 'Autre / Hors Suisse')], default='', help_text='Swiss canton (for the sales heatmap)', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='consent_nlpd',
            field=models.BooleanField(default=False, help_text='Swiss nLPD data-processing consent'),
        ),
        migrations.AddField(
            model_name='customer',
            name='consent_nlpd_at',
            field=models.DateTimeField(blank=True, help_text='When nLPD consent was given', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('b2c', 'Particulier (B2C)'), ('b2b_distributor', 'Distributeur (B2B)'), ('b2b_hospitality', 'Hôtel / Corporate (B2B)')], default='b2c', help_text='Segment used across KPIs (B2C / B2B distributor / B2B hospitality)', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='npa',
            field=models.CharField(blank=True, default='', help_text='Swiss postal code (NPA)', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='source_acquisition',
            field=models.CharField(blank=True, default='', help_text='Acquisition source (utm_source or similar)', max_length=100),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='client_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='company_name',
            field=models.CharField(default='Temp', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='segment',
            field=models.CharField(choices=[('distributor', 'Distributeur'), ('hotel', 'Hôtel'), ('corporate', 'Corporate')], default='distributor', max_length=20),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Actif'), ('dormant', 'Dormant')], default='prospect', max_length=20),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='passwordresettoken',
            table='b2b_accounts',
        ),
    ]
