# Generated by Django 5.2.15 on 2026-06-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_canton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2baccount',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('prospect', 'Prospect'), ('active', 'Actif'), ('dormant', 'Dormant')], default='prospect', max_length=20),
        ),
    ]
