# Generated by Django 5.2.15 on 2026-07-02 13:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_pending_b2b_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_id', models.CharField(db_index=True, help_text='Anonymous consent identifier stored in the cookie', max_length=64)),
                ('necessary', models.BooleanField(default=True)),
                ('analytics', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('policy_version', models.CharField(default='1.0', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
