# Generated by Django 5.2.15 on 2026-06-11 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField(help_text='Date pour laquelle on prédit (ex: 2026-07-01)')),
                ('predicted_quantity', models.PositiveIntegerField(help_text="Nombre d'unités prédites pour cette date")),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Confiance du modèle (0.0 à 1.0)', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date du calcul de la prévision')),
                ('product', models.ForeignKey(help_text='Produit', on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='shop.product')),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(help_text="Description de l'alerte")),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Niveau de sévérité', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Produit', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='shop.product')),
                ('forecast', models.ForeignKey(help_text='Prévision associée', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='forecasting.forecast')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
