# Generated by Django 5.2 on 2026-06-28 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0003_alter_stock_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CockpitObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_revenue_chf", models.PositiveIntegerField(default=3000)),
                ("monthly_revenue_chf", models.PositiveIntegerField(default=80000)),
                ("monthly_capacity_units", models.PositiveIntegerField(default=50000)),
                (
                    "target_margin_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        help_text="Target gross margin, in percent.",
                        max_digits=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif cockpit",
                "verbose_name_plural": "Objectifs cockpit",
            },
        ),
        migrations.CreateModel(
            name="ProductTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_units", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cockpit_target",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif produit",
                "verbose_name_plural": "Objectifs produits",
            },
        ),
    ]
