# Generated by Django 5.2 on 2026-06-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cockpit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CantonTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canton",
                    models.CharField(
                        choices=[
                            ("ZH", "Zürich"),
                            ("BE", "Berne"),
                            ("LU", "Lucerne"),
                            ("UR", "Uri"),
                            ("SZ", "Schwyz"),
                            ("OW", "Obwald"),
                            ("NW", "Nidwald"),
                            ("GL", "Glaris"),
                            ("ZG", "Zoug"),
                            ("FR", "Fribourg"),
                            ("SO", "Soleure"),
                            ("BS", "Bâle-Ville"),
                            ("BL", "Bâle-Campagne"),
                            ("SH", "Schaffhouse"),
                            ("AR", "Appenzell Rhodes-Extérieures"),
                            ("AI", "Appenzell Rhodes-Intérieures"),
                            ("SG", "Saint-Gall"),
                            ("GR", "Grisons"),
                            ("AG", "Argovie"),
                            ("TG", "Thurgovie"),
                            ("TI", "Tessin"),
                            ("VD", "Vaud"),
                            ("VS", "Valais"),
                            ("NE", "Neuchâtel"),
                            ("GE", "Genève"),
                            ("JU", "Jura"),
                            ("XX", "Autre / Hors Suisse"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("monthly_revenue_chf", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Objectif canton",
                "verbose_name_plural": "Objectifs cantons",
            },
        ),
    ]
