# Generated by Django 5.2 on 2026-06-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_area", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraddress",
            name="canton",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ZH", "Zürich"),
                    ("BE", "Berne"),
                    ("LU", "Lucerne"),
                    ("UR", "Uri"),
                    ("SZ", "Schwyz"),
                    ("OW", "Obwald"),
                    ("NW", "Nidwald"),
                    ("GL", "Glaris"),
                    ("ZG", "Zoug"),
                    ("FR", "Fribourg"),
                    ("SO", "Soleure"),
                    ("BS", "Bâle-Ville"),
                    ("BL", "Bâle-Campagne"),
                    ("SH", "Schaffhouse"),
                    ("AR", "Appenzell Rhodes-Extérieures"),
                    ("AI", "Appenzell Rhodes-Intérieures"),
                    ("SG", "Saint-Gall"),
                    ("GR", "Grisons"),
                    ("AG", "Argovie"),
                    ("TG", "Thurgovie"),
                    ("TI", "Tessin"),
                    ("VD", "Vaud"),
                    ("VS", "Valais"),
                    ("NE", "Neuchâtel"),
                    ("GE", "Genève"),
                    ("JU", "Jura"),
                    ("XX", "Autre / Hors Suisse"),
                ],
                default="",
                help_text="Swiss canton, used for the sales heatmap.",
                max_length=2,
            ),
        ),
    ]
