# Generated by Django 5.2.15 on 2026-06-11 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(help_text='Numéro unique de commande (ex: CMD-2024-0001)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Statut de la commande', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Prix total en CHF', max_digits=10)),
                ('shipping_address', models.TextField(help_text='Adresse de livraison')),
                ('billing_address', models.TextField(help_text='Adresse de facturation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Client qui a fait la commande', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text="Nombre d'unités commandées")),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix unitaire au moment de la commande', max_digits=10)),
                ('order', models.ForeignKey(help_text='Commande', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.order')),
                ('product', models.ForeignKey(help_text='Produit commandé', on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent', models.CharField(help_text='ID PaymentIntent de Stripe', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant en CHF', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Statut du paiement', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Date du paiement réussi', null=True)),
                ('order', models.OneToOneField(help_text='Commande payée', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='checkout.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
