# Generated by Django 5.2.15 on 2026-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='campaign_period',
            field=models.CharField(blank=True, default='', help_text='Seasonal campaign (e.g. Noel, Saint-Valentin) for seasonality KPI', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('b2c', 'B2C'), ('b2b', 'B2B')], default='b2c', help_text='Sales channel (b2c/b2b) for cockpit splitting', max_length=3),
        ),
    ]
