# Generated by Django 5.2 on 2026-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_order_campaign_period_order_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("CHF", "Franc suisse")],
                default="CHF",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("CHF", "Franc suisse")],
                default="CHF",
                max_length=3,
            ),
        ),
    ]
