# Generated by Django 5.2.15 on 2026-06-11 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(help_text="Nom de l'entreprise", max_length=255)),
                ('contact_name', models.CharField(help_text='Nom du responsable', max_length=255)),
                ('email', models.EmailField(help_text='Email de contact', max_length=254)),
                ('phone', models.CharField(help_text='Numéro de téléphone', max_length=20)),
                ('message', models.TextField(help_text='Détails de la demande de partenariat')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='État de la demande', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Client (optionnel, peut être anonyme)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Request',
                'verbose_name_plural': 'Business Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
