# Generated by Django 5.2 on 2026-06-11 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('estimated_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('occasion', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('in_progress', 'En cours'), ('converted', 'Convertie'), ('refused', 'Refusée')], default='new', max_length=20)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.adminuser')),
            ],
            options={
                'db_table': 'b2b_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='b2b_request_status_d84a30_idx'), models.Index(fields=['-created_at'], name='b2b_request_created_7f7954_idx')],
            },
        ),
    ]
