# Generated by Django 5.2.15 on 2026-06-23 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shop', '0003_alter_stock_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wants_marketing', models.BooleanField(default=False)),
                ('marketing_consent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'b2b_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_b2b_available', models.BooleanField(default=True)),
                ('availability_status', models.CharField(choices=[('active', 'Actif'), ('new', 'Nouveauté'), ('coming_soon', 'Bientôt')], default='active', max_length=20)),
                ('moq', models.PositiveIntegerField(default=24, help_text='Minimum order quantity for B2B')),
                ('b2b_unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Pro unit price in CHF; falls back to the SKU price if empty', max_digits=10, null=True)),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_info', to='shop.sku')),
            ],
            options={
                'db_table': 'b2b_product_info',
            },
        ),
        migrations.CreateModel(
            name='CustomizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_engraved', models.BooleanField(default=False)),
                ('inner_packaging', models.CharField(blank=True, default='', max_length=120)),
                ('outer_packaging', models.CharField(blank=True, default='', max_length=120)),
                ('grammage', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('quote', 'Devis demandé'), ('order', 'Commande')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_requests', to='accounts.b2baccount')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customization_requests', to='shop.sku')),
            ],
            options={
                'db_table': 'b2b_customization_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_json', models.JSONField(blank=True, default=list)),
                ('moq_reached', models.BooleanField(default=False)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('converted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_simulations', to='accounts.b2baccount')),
            ],
            options={
                'db_table': 'b2b_quote_simulations',
                'ordering': ['-created_at'],
            },
        ),
    ]
