# Generated by Django 5.2.15 on 2026-06-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_b2brequest_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2brequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b2brequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('converted', 'Converti'), ('refused', 'Refusé')], default='new', max_length=20),
        ),
    ]
